### ISSUE TITLE
Update path for XCode 6.3

### ISSUE THREAD

**Issue by araid** [mthiesen/Xcode_copy_line#6]
the Plugin folder is not in Application support anymore, but in ```/Applications/Xcode.app/Contents/PlugIns```

**Comment by kreeger** [comment]
@araid This doesn't seem to be the case for me; no custom plugin I drop into the Application Bundle's `Contents/PlugIns` directory gets loaded, whereas everything in the previous Application Support-based directory does.

**Comment by araid** [comment]
Interesting. In my case, after the Yosemite update the original directory didn't exist anymore. Well I guess the note is here, in case it's useful to someone in the future.
